import Head from 'next/head'
import Image from 'next/image'
import {
  Container,
  Grid,
  Typography,
  useTheme,
  Box,
  TextField,
  InputAdornment,
  Button,
} from '@mui/material'
import SearchIcon from '@mui/icons-material/Search'

export default function Home() {
  const theme = useTheme()
  console.log(theme)
  return (
    <>
      <Head>
        <title>INDEPTH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Box sx={{ height: '40vh', position: 'relative' }}>
            <Image
              alt="tree visualization"
              src="/tree.svg"
              fill
              style={{
                objectFit: 'cover',
                opacity: '0.2',
                position: 'absolute',
                zIndex: '0',
              }}
            />
            <Box
              sx={{
                display: 'flex',
                height: '100%',
                justifyContent: 'center',
                alignItems: 'center',
                position: 'relative',
                zIndex: '1',
              }}
            >
              <Grid container justifyContent={'center'}>
                <Grid item>
                  <Typography variant="h2" sx={{ backdropFilter: 'blur(2px)' }}>
                    INDEPTH
                  </Typography>
                </Grid>
                <Grid item>
                  <Typography
                    variant="h2"
                    sx={{
                      color: 'primary.main',
                      backdropFilter: 'blur(2px)',
                    }}
                  >
                    .social
                  </Typography>
                </Grid>
              </Grid>
            </Box>
          </Box>
          <Grid container>
            <Grid
              item
              xs={12}
              sx={{
                display: 'flex',
                justifyContent: 'center',
                paddingTop: '2rem',
              }}
            >
              <TextField
                sx={{ width: 'min(400px, 100%)' }}
                variant="standard"
                id="input-topic-name"
                label="search the topic"
                InputProps={{
                  endAdornment: (
                    <InputAdornment position="end">
                      <SearchIcon />
                    </InputAdornment>
                  ),
                }}
              />
            </Grid>
            <Grid
              item
              xs={12}
              sx={{
                display: 'flex',
                justifyContent: 'center',
                paddingTop: '2rem',
              }}
            >
              <Button variant="outlined" sx={{ margin: '0 1rem' }}>
                sign in
              </Button>
              <Button variant="outlined" sx={{ margin: '0 1rem' }}>
                sign up
              </Button>
            </Grid>
          </Grid>
        </Container>
      </main>
    </>
  )
}
